/* Template catalog — drives gallery cards (EN + AR) */
window.IBRA_CATALOG = [
  {
    id: "gym-iron",
    path: "templates/gym-iron/index.html",
    category: "gym",
    tags: ["Gym", "Fitness"],
    en: { title: "Iron Forge Gym", text: "Bold dark gym site — memberships, classes, trainers, join CTA." },
    ar: { title: "نادي آيرون فورج", text: "موقع نادي رياضي قوي — عضويات، حصص، مدربين، ودعوة للانضمام." },
  },
  {
    id: "gym-flow",
    path: "templates/gym-flow/index.html",
    category: "gym",
    tags: ["Gym", "Wellness"],
    en: { title: "Flow Wellness", text: "Bright wellness studio — yoga, pilates, calm booking-focused layout." },
    ar: { title: "فلاو ويلنس", text: "استوديو عافية مشرق — يوغا وبيلاتس وحجز بهدوء واحتراف." },
  },
  {
    id: "gym-box",
    path: "templates/gym-box/index.html",
    category: "gym",
    tags: ["Gym", "CrossFit"],
    en: { title: "Box 42 Training", text: "Industrial CrossFit box — WODs, coaches, community energy." },
    ar: { title: "بوكس 42", text: "صالة كروس فت صناعية — تمارين يومية، مدربين، وطاقة جماعية." },
  },
  {
    id: "market-fresh",
    path: "templates/market-fresh/index.html",
    category: "market",
    tags: ["Market", "Grocery"],
    en: { title: "FreshBasket Market", text: "Colorful supermarket — departments, weekly deals, delivery promo." },
    ar: { title: "فريش باسكت", text: "سوبرماركت ملون — أقسام، عروض أسبوعية، وتوصيل." },
  },
  {
    id: "market-city",
    path: "templates/market-city/index.html",
    category: "market",
    tags: ["Market", "Hyper"],
    en: { title: "CityMart Hyper", text: "Modern hypermarket — categories grid, hours, store finder feel." },
    ar: { title: "سيتي مارت", text: "هايبر ماركت حديث — شبكة أقسام، أوقات العمل، وروح المتجر." },
  },
  {
    id: "market-organic",
    path: "templates/market-organic/index.html",
    category: "market",
    tags: ["Market", "Organic"],
    en: { title: "GreenLeaf Organic", text: "Soft organic grocery — farm-to-table story and clean product cards." },
    ar: { title: "جرين ليف عضوي", text: "بقالة عضوية هادئة — قصة من المزرعة وبطاقات منتجات نظيفة." },
  },
  {
    id: "clinic-care",
    path: "templates/clinic-care/index.html",
    category: "clinic",
    tags: ["Clinic", "Medical"],
    en: { title: "CarePlus Clinic", text: "Trusted medical clinic — services, doctors, appointment CTA." },
    ar: { title: "عيادة كير بلس", text: "عيادة طبية موثوقة — خدمات، أطباء، وحجز موعد." },
  },
  {
    id: "clinic-dental",
    path: "templates/clinic-dental/index.html",
    category: "clinic",
    tags: ["Clinic", "Dental"],
    en: { title: "BrightSmile Dental", text: "Fresh dental clinic — whitening, family care, smile-focused hero." },
    ar: { title: "ابتسامة مشرقة", text: "عيادة أسنان عصرية — تبييض، رعاية عائلية، وتركيز على الابتسامة." },
  },
  {
    id: "clinic-family",
    path: "templates/clinic-family/index.html",
    category: "clinic",
    tags: ["Clinic", "Family"],
    en: { title: "Family Health Hub", text: "Warm family practice — pediatrics, labs, multi-service layout." },
    ar: { title: "مركز صحة العائلة", text: "عيادة عائلية دافئة — أطفال، مختبرات، وخدمات متعددة." },
  },
  {
    id: "restaurant",
    path: "templates/restaurant/index.html",
    category: "restaurant",
    tags: ["Food", "Fine"],
    en: { title: "Olive & Ember", text: "Warm fine-dining restaurant — menu cards and reserve CTA." },
    ar: { title: "أوليف آند إمبر", text: "مطعم راقٍ دافئ — بطاقات قائمة وزر حجز طاولة." },
  },
  {
    id: "restaurant-bistro",
    path: "templates/restaurant-bistro/index.html",
    category: "restaurant",
    tags: ["Food", "Bistro"],
    en: { title: "Noon Bistro", text: "Light modern bistro — brunch energy, dishes, location strip." },
    ar: { title: "نون بيسترو", text: "بيسترو حديث خفيف — برانش، أطباق، وشريط موقع." },
  },
  {
    id: "restaurant-grill",
    path: "templates/restaurant-grill/index.html",
    category: "restaurant",
    tags: ["Food", "Grill"],
    en: { title: "Charcoal Grill House", text: "Smoky grill house — meat cuts, combos, bold night vibe." },
    ar: { title: "بيت الشواء", text: "مطعم مشاوي — قطع لحم، وجبات، وأجواء ليلية جريئة." },
  },
  {
    id: "saas-landing",
    path: "templates/saas-landing/index.html",
    category: "business",
    tags: ["SaaS", "Startup"],
    en: { title: "NovaPulse SaaS", text: "Dark product landing for apps and tools — strong CTA and features." },
    ar: { title: "نوفا بالس", text: "صفحة منتج داكنة للتطبيقات والأدوات — دعوة واضحة ومميزات." },
  },
  {
    id: "portfolio",
    path: "templates/portfolio/index.html",
    category: "creative",
    tags: ["Portfolio", "Creative"],
    en: { title: "Creative Portfolio", text: "Editorial portfolio for freelancers and personal brands." },
    ar: { title: "بورتفوليو إبداعي", text: "معرض أعمال تحريري للمستقلين والعلامات الشخصية." },
  },
  {
    id: "ecommerce",
    path: "templates/ecommerce/index.html",
    category: "shop",
    tags: ["Shop", "Products"],
    en: { title: "Forma Store", text: "Clean product grid for small shops and product launches." },
    ar: { title: "متجر فورما", text: "شبكة منتجات نظيفة للمتاجر الصغيرة وإطلاق المنتجات." },
  },
  {
    id: "salon-luxe",
    path: "templates/salon-luxe/index.html",
    category: "salon",
    tags: ["Salon", "Beauty"],
    en: { title: "Luxe Hair Studio", text: "Elegant salon — services menu, stylists, book appointment." },
    ar: { title: "لوكس للشعر", text: "صالون أنيق — قائمة خدمات، مصففين، وحجز موعد." },
  },
  {
    id: "cafe-brew",
    path: "templates/cafe-brew/index.html",
    category: "restaurant",
    tags: ["Cafe", "Coffee"],
    en: { title: "Brew & Bean Cafe", text: "Cozy coffee shop — drinks menu, hours, neighborhood charm." },
    ar: { title: "برو آند بين", text: "مقهى دافئ — قائمة مشروبات، أوقات، وأجواء الحي." },
  },
  {
    id: "realestate-keys",
    path: "templates/realestate-keys/index.html",
    category: "business",
    tags: ["Real Estate", "Homes"],
    en: { title: "Keystone Homes", text: "Real estate agency — featured listings, agents, contact." },
    ar: { title: "كي ستون للعقارات", text: "وكالة عقارية — عقارات مميزة، وسطاء، وتواصل." },
  },
];
